[project]
name = "aws_data"
requires-python = ">=3.10,<3.15"
version = "0.1.0"
dependencies = [
    "dagster==1.13.20",
    "dagster-aws",
    "dagster-deltalake-polars>=0.29.20",
    "dagster-k8s>=0.29.20",
]

[dependency-groups]
dev = [
    "dagster-dg-cli",
    "dagster-webserver",
    "ruff>=0.16.5",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
force-include = { "pyproject.toml" = "pyproject.toml" }

[tool.ruff]
src = ["src"]

[tool.ruff.lint.isort]
known-first-party = ["aws_data"]

[tool.dg]
directory_type = "project"

[tool.dg.project]
root_module = "aws_data"
registry_modules = [
    "aws_data.components.*",
]


